config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :authors


  # setting the home page
  root to: 'blog/posts#index'



  # expects: /author/posts/jimbob
  namespace :authors do

    get '/account' => 'accounts#edit', as: :account

    # when account info form is submitted
    put '/info' => 'accounts#update_info', as: :info

    # when password form is submitted
    put '/change_password' => 'accounts#change_password', as: :change_password

    #maps http request actions to model
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end

  scope module: 'blog' do
    
    #map get requests    
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts

    # 'posts/jimbob' => params[:id] == 'jimbob'
    get 'posts/:id' => 'posts#show', as: :post
    
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_featured_post_card.html.erb
<!--whole row when small, else 1/3-->
<div class="col-sm-12 col-md-6 col-lg-4 mb-4">
    <div class="card card-featured shadow mx-auto">
            
        <%= link_to post do %>
    
        <img alt="" class="card-img-top card-topper" src="#{<% post.banner_image_url %>}">
    
            <div class="card-body card-block">
                
                <!--POST TITLE-->
                <h5 class="card-title"><%= post.title %></h5>
                
                <!--DESCRIPTION-->
                <h5 class="card-text text-thin text-muted">
                    <%= truncate(post.description, length: 75) %>
                </h5>

                <!--AUTHOR-->
                <small class="text-thin"><%= post.author.name %></small>    
                <p>
                    <small class="card-text text-muted text-thin">Published: <%= post.date_published %></small>    
                    <small> | Updated: <%= post.date_updated %></small>
                </p>
             
            </div>
            <% end %>
        </div>
    </div>
    

app/views/partials/_footer.html.erb
<footer>
    <div class="container mt-3 mb-0">
        <p>
            &copy; My Site 2018
        </p>
    </div>
</footer>

app/views/partials/_jumbotron.html.erb
<% if params[:controller] == 'home' %>

<!--jumbotron-fluid fills container and adds rounded bottom corners-->
<div class="jumbotron jumbotron-fluid shadow"> 
    <div class="container">

        <h1 class="display-4">Simple. Elegant. Jumbotron.</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    
        <p class="lead">
            <a href="#" class="btn btn-primary btn-lg" role="button">Learn More</a>
        </p>
    </div>
</div>

<% end %>

          
          

app/views/partials/_modal.html.erb
<!--can only have one modal at a time-->
<div class="modal fade" id="TEST_MODAL">
    <div class="modal-dialog">
        <div class="modal-content">
                    
            <!--header-->
            <div class="modal-header">
                      
                <!--Title-->
                <h2 class="modal-title">Please Confirm!</h2>
                <!--make dismissible "x button"-->
                <button data-dismiss="modal" type="button" class="close"><span aria-hidden="true">&times;</span></button>
          
            </div>
          
            <!--body-->
            <div class="modal-body">
                <p>This is the modal body</p>
            </div>
          
            <!--footer-->
            <div class="modal-footer">
                <button data-dismiss="modal"  type="button" class="btn btn-secondary">Confirm</button>
            </div>
        </div>
    </div>
</div>

app/views/partials/_navbar.html.erb
<!--
NAV BAR
navbar-expand-(min size for expand)
-->
<!--
    <nav class="navbar navbar-expand-sm navbar-dark shadow bg-gradient-primary">
    <nav class="navbar navbar-expand-sm navbar-light bg-faded">
-->
    
<nav class="navbar navbar-expand-sm navbar-dark shadow sticky-top">
    
    <!--Website Title-->
    <a href="<%= root_path %>" class="navbar-brand align-bottom py-0">
        <span class="nav-item nav-accent">A</span>
        <span class="nav-item">W</span>
        <span class="nav-item nav-accent">S
                
            <!--

                <img src="/assets/logo_w.png" class="nav-item nav-logo mx-0 mb-1" alt="">
            -->
                <img class="nav-item nav-logo mx-0 mb-1" alt="" src="<%= asset_path("logo_w.png") %>">
            
            
        </span>
    </a>
        
        
        
    </div>


    <!--button for collapsed mode-->
    <button class="navbar-toggler" data-toggle="collapse" data-target="#NAVBAR_MINI_INCLUDE">
        <span class="navbar-toggler-icon"><!--&#9776;--></span>
    </button>

    <!--MOBILE FIRST APPROACH 
        so it renders the stuff above first and this is the 'hidden content'
    -->
    <div class="collapse navbar-collapse" id="NAVBAR_MINI_INCLUDE">
        
        <div class="navbar-nav ml-auto">

            <%= link_to "Home", root_path, class: "nav-link nav-item #{yield(:blog_active)}" %>
            <%= link_to "About", about_path, class: "nav-link nav-item #{yield(:about_active)}" %>
            <%= link_to "Contact", contact_path, class: "nav-link nav-item #{yield(:contact_active)}" %>
            
            <% if author_signed_in? %>
          
                
                <!--dropdown menu in nav
                be sure to use separate and nested elements for 
                .nav-item and .nav-link as shown below.
                -->
                
                <div class="nav-item dropdown">
                    <a href="#" data-toggle="dropdown" class="author-nav nav-link dropdown-toggle <%=yield(:author) %>">
                        
                        <%= current_author.display_name %>
                        <img src="<%= current_author.gravatar_img_url %>" alt="">
    
                    </a>
    
                    
                    <div class="dropdown-menu">
    
                        <%= link_to "My Posts", authors_posts_path, class: "dropdown-item" %>
                        <%= link_to "Account", authors_account_path, class: "dropdown-item" %>
                        
                        <div class="dropdown-divider"></div>
                        <%= link_to "Logout", destroy_author_session_path, method: :delete, class: "dropdown-item" %>
                        
                    </div>
                </div>
            <% end %>
        </div>

    </div>

    <!--
        items that should disappear on collapse
        <div class="collapse navbar-collapse">
            <!-- ml-auto = margin left auto (pushes to right)--
            <div class="ml-auto">
                
                <!--
                    list for nav bar right
                    <div class="navbar-nav">
                        <a href="#" class="nav-link nav-item">Products</a>
                    </div>
                --
                
                <!--forms in navbar--
                <form class="form-inline">
                    <!--
                        <input class="form-control mr-2" type="text" placeholder="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    --
                    
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">@</span>
                        </div>
                        <input type="text" class="form-control" placeholder="Username">
                    </div>
                    
                </form>
            </div>
            
        </div>
    -->
</nav>



<!--

    .navbar-brand for your company, product, or project name.
    .navbar-nav for a full-height and lightweight navigation (including support for dropdowns).
    .navbar-toggler for use with our collapse plugin and other navigation toggling behaviors.
    .form-inline for any form controls and actions.
    .navbar-text for adding vertically centered strings of text.
    .collapse.navbar-collapse for grouping and hiding navbar contents by a parent breakpoint.
    
    Sometimes you want to use the collapse plugin to trigger hidden content elsewhere on the page. 
    <div class="pos-f-t">
      <div class="collapse" id="navbarToggleExternalContent">
        <div class="bg-dark p-4">
          <h4 class="text-white">Collapsed content</h4>
          <span class="text-muted">Toggleable via the navbar brand.</span>
        </div>
      </div>
      <nav class="navbar navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent">
          <span class="navbar-toggler-icon"></span>
        </button>
      </nav>
    </div>

-->    

app/views/partials/_normal_post_card.html.erb
<!--whole row when small, else 1/3-->
<div class="col-sm-12 col-md-8 mb-0">
        <div class="card post-card">
                
            <%= link_to post do %>
        
            <div class="row m-0 p-0">

                <div class="col-auto m-0 p-0 align-left">
                    <img alt="" class="card-topper" src="#{<% post.banner_image_url %>}">
                
                </div>
                <div class="col pt-2">
    
                    <div class="card-block">
                        
                        <!--POST TITLE-->
                        <h5 class="card-title pb-1 m-0"><%= post.title %></h5>
                        
                        <!--DESCRIPTION-->
                        <h5 class="card-text text-thin text-muted">
                            <%= truncate(post.description, length: 75) %>
                        </h5>
                        
                        <!--AUTHOR-->
                        <small class="text-thin"><%= post.author.name %></small>    
                        <p>
                            <small class="card-text text-muted text-thin">Published: <%= post.date_published %></small>    
                            <small> | Updated: <%= post.date_updated %></small>
                        </p>
                        
                    </div>
                </div>
            </div>
            
            
            
            <% end %>
        </div>
        </div>
        