config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :authors


  # setting the home page
  root to: 'blog/posts#index'



  # expects: /author/posts/jimbob
  namespace :authors do

    get '/account' => 'accounts#edit', as: :account

    # when account info form is submitted
    put '/info' => 'accounts#update_info', as: :info

    # when password form is submitted
    put '/change_password' => 'accounts#change_password', as: :change_password

    #maps http request actions to model
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end

  scope module: 'blog' do
    
    #map get requests    
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts

    # 'posts/jimbob' => params[:id] == 'jimbob'
    get 'posts/:id' => 'posts#show', as: :post
    
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  #attr_accessible :email, :password, :password_confirmation, :remember_me




  has_many :posts

  validates_presence_of :name, on: :update


  def change_password(attributes)
    update(password: attributes[:new_password], password_confirmation: attributes[:new_password_confirmation])
  end


  def gravatar_img_url
    "https://www.gravatar.com/avatar/#{gravatar_hash}"
  end

  def display_name
    if name.present?
      name
    else
      "Author ##{id}"
    end
  end

  private
  
  def gravatar_hash
    Digest::MD5.hexdigest(email.downcase)
  end

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
    # anything in the authors namespace requires authentication before any action
    before_action :authenticate_author!
end

app/controllers/authors/accounts_controller.rb
module Authors
    class AccountsController < AuthorController
        def edit
        end
    
        def update_info
            #TODO: error handling
            if current_author.update(author_info_params)
                flash[:success] = "Successfully Saved Info!"    
            else
                flash[:danger] = current_author.display_error_messages
            end
            redirect_to authors_account_path
        end
        
        def change_password
            author = current_author
            if author.valid_password?(author_password_params[:current_password])
            
                if author.change_password(author_password_params)
                    # devise automatically signs out when changing password
                    sign_in(author, bypass: true)
                    flash[:success] = 'Successfully Changed Password!'
                else
                    flash[:danger] = author.errors.full_messages.join('.  ') << '.'
            
                end
            
            else

                flash[:danger] = 'Current Password Incorrect' 
                
            end
            redirect_to authors_account_path
        
            #breakpoint
            #binding.pry
        end

        private
        def author_info_params
            params.require(:author).permit(:name, :email, :bio)
        end

        def author_password_params
            params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
        end
    
    end
end

app/controllers/authors/posts_controller.rb
# @var makes @var available in corresponding view

module Authors

    class PostsController < AuthorController
  
      # run set_post before show, edit, update and destroy
      before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
    
      # GET /posts
      # GET /posts.json
      def index
        @posts = current_author.posts.most_recent_c
        #@posts = Post.all
      end
    
      # GET /posts/1
      # GET /posts/1.json
      def show


      end

      # GET /posts/new
      def new
        @post = current_author.posts.new
      end
    
      # GET /posts/1/edit
      def edit

      end


      def publish
        @post.publish
        redirect_to authors_posts_url
      end

      def unpublish
        @post.unpublish
        redirect_to authors_posts_url
      end
    
      # POST /posts
      # POST /posts.json


      def create
        @post = current_author.posts.new(post_params)
        respond_to do |format|
          if @post.save
            format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # PATCH/PUT /posts/1
      # PATCH/PUT /posts/1.json
      def update
        respond_to do |format|
          if @post.update(post_params)
            format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
            format.json { render :show, status: :ok, location: @post }
          else
            format.html { render :edit }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # DELETE /posts/1
      # DELETE /posts/1.json
      def destroy
        print 'destroyed'
        @post.destroy
        respond_to do |format|
          format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_post
          #looks up a post in the database by id number in url
        
          #@post = Post.all.friendly.find(params[:id])
          @post = current_author.posts.friendly.find(params[:id])
        end
    
        def post_params
          params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
        end
    end
    
  end
  

app/views/authors/accounts/edit.html.erb
<div class="row">
    <!--basic info-->
    <div class="col-md-6">
    
        <%= form_tag authors_info_path, method: :put do %>
        <%= fields_for :author do |f| %>
        <div class="card">
            
            <div class="card-header">
                <h4>Account Info</h4>
            </div>
    
            <ul class="list-group list-group-flush">
                <li class="list-group-item">

                    <%= image_tag(current_author.gravatar_img_url) %>

                    <small class="text-muted">(Fetched from Gravatar)</small>


                </li>
                <li class="list-group-item">
                    <div class="field">
                        <%= f.label :name %>
                        <%= f.text_field :name, value: current_author.name, class: 'form-control' %>
                    </div>
                </li>
            
                <li class="list-group-item">
                    <div class="field">
                        <%= f.label :email %>
                        <%= f.email_field :email, value: current_author.email, class: 'form-control' %>
                    </div>
                </li>

                <li class="list-group-item">
                    <div class="field">
                        <%= f.label :bio %>
                        <%= f.text_area :bio, value: current_author.bio, class: 'form-control' %>
                    </div>
                </li>
                <li class="ml-auto list-group-item">

                    
                    <%= f.submit '', :class => "hidden invisible p-0 m-0", :id => 'change_info_submit_button', :style => "padding: 0px; margin:0px; width: 0px; height: 0px;" %>
                    <%= link_to 'Update Info', "", :onclick => "$('#change_info_submit_button').click();", class: 'btn btn-default' %>
                    
                </li>
            </ul>
        </div>             
        <% end %>
        <% end %>


    
    </div>
        
    <!--CHANGE PASSWORD-->
    
    <div class="col-md-6">
        <%= form_tag authors_change_password_path, method: :put do %>

        <%= fields_for :author do |f| %>
        
        <div class="card">
    
            <div class="card-header">
                <h4>Passowrd</h4>
            </div>
            
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="field">
                      <%= f.label :current_password %>
                      <%= f.password_field :current_password, class: 'form-control' %>
                    </div>
                </li>
    
                <li class="list-group-item">
                    <div class="field">
                        <%= f.label :new_password %>
                        <%= f.password_field :new_password, class: 'form-control' %>
                    </div>
                </li>
    
                <li class="list-group-item">
                    <div class="field">
                        <%= f.label :new_password_confirmation %>
                        <%= f.password_field :new_password_confirmation, class: 'form-control' %>
                    </div>
                </li>

                <li class="ml-auto list-group-item">


                    <%= f.submit '', :class => "hidden invisible p-0 m-0", :id => 'change_password_submit_button', :style => "padding: 0px; margin:0px; width: 0px; height: 0px;" %>
                    <%= link_to 'Update Password', "", :onclick => "$('#change_password_submit_button').click();", class: 'btn btn-default' %>
                     
                </li>
            </ul>
        </div>   
        <% end %>
        <% end %>

    </div>
    
</div>