config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :authors


  # setting the home page
  root to: 'blog/posts#index'



  # expects: /author/posts/jimbob
  namespace :authors do

    get '/account' => 'accounts#edit', as: :account

    # when account info form is submitted
    put '/info' => 'accounts#update_info', as: :info

    # when password form is submitted
    put '/change_password' => 'accounts#change_password', as: :change_password

    #maps http request actions to model
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end

  scope module: 'blog' do
    
    #map get requests    
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts

    # 'posts/jimbob' => params[:id] == 'jimbob'
    get 'posts/:id' => 'posts#show', as: :post
    
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  #attr_accessible :email, :password, :password_confirmation, :remember_me




  has_many :posts

  validates_presence_of :name, on: :update


  def change_password(attributes)
    update(password: attributes[:new_password], password_confirmation: attributes[:new_password_confirmation])
  end


  def gravatar_img_url
    "https://www.gravatar.com/avatar/#{gravatar_hash}"
  end

  def display_name
    if name.present?
      name
    else
      "Author ##{id}"
    end
  end

  private
  
  def gravatar_hash
    Digest::MD5.hexdigest(email.downcase)
  end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#  published        :boolean          default(FALSE)
#  published_at     :datetime

class Post < ApplicationRecord
    acts_as_taggable # Alias for acts_as_taggable_on :tags
    
    extend FriendlyId
    friendly_id :title, use: :slugged

    belongs_to :author

    PER_PAGE = 6
  
    scope :published, -> { where(published: true) }

    #get most recent
    scope :most_recent_u, -> { order(updated_at: :desc) }
    scope :most_recent_p, -> { order(published_at: :desc) }
    scope :most_recent_c, -> { order(created_at: :desc) }
        
    scope :recent_paginated, -> (page) { most_recent_p.paginate(page: page, per_page: PER_PAGE) }
    scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }
    
    # perform a paginated query 
    # or, use an explicit "per page" limit:
    scope :list_for, -> (page, tag) do
        recent_paginated(page).with_tag(tag)
    end

    def should_generate_new_friendly_id?
        #rails syntax
        title_changed?
    end

    def _get_display(val, nil_message)
        if val.present?
            val.strftime('%-b %-d %Y')
        else
            nil_message
        end
    end

    def date_published
        _get_display(published_at, 'Not Published Yet')
    end

    def date_updated
        _get_display(updated_at, 'Not Updated Yet')
    end
    
    def date_created
        _get_display(created_at, 'Not Created Yet')
    end
    
    def publish
        update(published: true, published_at: Time.now)
    end
    
    def unpublish  
        update(published: false, published_at: nil)
    end

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
    # anything in the authors namespace requires authentication before any action
    before_action :authenticate_author!
end

app/controllers/authors/accounts_controller.rb
module Authors
    class AccountsController < AuthorController
        def edit
        end
    
        def update_info
            #TODO: error handling
            if current_author.update(author_info_params)
                flash[:success] = "Successfully Saved Info!"    
            else
                flash[:danger] = current_author.display_error_messages
            end
            redirect_to authors_account_path
        end
        
        def change_password
            author = current_author
            if author.valid_password?(author_password_params[:current_password])
            
                if author.change_password(author_password_params)
                    # devise automatically signs out when changing password
                    sign_in(author, bypass: true)
                    flash[:success] = 'Successfully Changed Password!'
                else
                    flash[:danger] = author.errors.full_messages.join('.  ') << '.'
            
                end
            
            else

                flash[:danger] = 'Current Password Incorrect' 
                
            end
            redirect_to authors_account_path
        
            #breakpoint
            #binding.pry
        end

        private
        def author_info_params
            params.require(:author).permit(:name, :email, :bio)
        end

        def author_password_params
            params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
        end
    
    end
end

app/controllers/authors/posts_controller.rb
# @var makes @var available in corresponding view

module Authors

    class PostsController < AuthorController
  
      # run set_post before show, edit, update and destroy
      before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
    
      # GET /posts
      # GET /posts.json
      def index
        @posts = current_author.posts.most_recent_c
        #@posts = Post.all
      end
    
      # GET /posts/1
      # GET /posts/1.json
      def show


      end

      # GET /posts/new
      def new
        @post = current_author.posts.new
      end
    
      # GET /posts/1/edit
      def edit

      end


      def publish
        @post.publish
        redirect_to authors_posts_url
      end

      def unpublish
        @post.unpublish
        redirect_to authors_posts_url
      end
    
      # POST /posts
      # POST /posts.json


      def create
        @post = current_author.posts.new(post_params)
        respond_to do |format|
          if @post.save
            format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # PATCH/PUT /posts/1
      # PATCH/PUT /posts/1.json
      def update
        respond_to do |format|
          if @post.update(post_params)
            format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
            format.json { render :show, status: :ok, location: @post }
          else
            format.html { render :edit }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # DELETE /posts/1
      # DELETE /posts/1.json
      def destroy
        print 'destroyed'
        @post.destroy
        respond_to do |format|
          format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_post
          #looks up a post in the database by id number in url
        
          #@post = Post.all.friendly.find(params[:id])
          @post = current_author.posts.friendly.find(params[:id])
        end
    
        def post_params
          params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
        end
    end
    
  end
  

app/controllers/blog/posts_controller.rb
# @var makes @var available in corresponding view

module Blog

  class PostsController < BlogController

    # GET /posts
    # GET /posts.json
    def index


      @posts = storage.list_for(params[:page], params[:tag])
      
      @featured_posts = storage
      
      #@posts = Post.all


    end
  
    # GET /posts/1
    # GET /posts/1.json
    def show
      #looks up a post in the database by id number in url
      @post = storage.friendly.find(params[:id])
    end

    private 
    
    
    def storage
      Post.published
    end


  
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_with(model: post, url: url, local: true) do |form| %>
  <% if post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
        <div class="card">

          <div class="card-header card-block pl-2">
            <h4 class="card-title">
          


              <% if @post.new_record? %>
                <h4 class="card-title">New Post</h4>
              <% else %>
                <h4 class="card-title">
                  <b>Edit</b>
                  <span class="thin-text">
                    <%= @post.title %>
                  </span>
                </h4>
              <% end %>

              <%#= yield(:page_title) %>
          </h4>
        </div>


        <ul class="list-group list-group-flush">
          <li class="list-group-item">

            <div class="field">
              <%= form.label :title %>
              <%= form.text_field :title, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">

            <div class="field">
                <%= form.label :banner_image_url %>
                <%= form.text_field :banner_image_url, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            
            <div class="field">
              <%= form.label :description %>
              <%= form.text_area :description, class: 'form-control' %>
            </div>

          </li>
          <li class="list-group-item">
            
            <div class="field">
              <%= form.label 'Tags' %>
              <%= form.text_area :tag_list, class: 'form-control' %>
            </div>

          </li>

        </ul>

        <div class="actions card-footer">
            <%= form.submit "Save Post", class: 'btn btn-success btn-block' %>
        </div>

      </div>

      <% if @post.persisted? %>
      <%= link_to 'Show', @post %> |
      
      <% end %>

      <%#= link_to 'Back', authors_posts_path %>

        




    
    </div>
    <div class="col-md-8">

      <div class="field">
        <%= form.text_area :body %>
      </div>

    </div>
  </div>

  
<% end %>

app/views/authors/posts/_post.html.erb
<tr>
    <td><%= link_to post.title, authors_post_path(post) %></td>
    <td></td>
    
    <!--method: :put because link_to is by default a get-->
    <% if post.published? %>
    <td>
    
            <%= link_to 'Unpublish', unpublish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-warning' %>
        </td>
        
    <% else %>
    <td>
    
            <%= link_to 'Publish', publish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary' %>
        </td>
        

    <% end %>
    
    
    <td>
    
        <%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-secondary' %>
    </td>
    <td>
    
        <%= link_to 'Remove', authors_post_path(post), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-sm btn-danger' %>
    
    </td>
</tr>

app/views/authors/posts/edit.html.erb
<!--
    only editing one post at a time
-->
<% provide(:page_title, "Edit: #{@post.title}") %>

<% provide(:author, "active") %>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

app/views/authors/posts/index.html.erb
<!--
all posts in database
-->
<% provide(:page_title, "All Posts") %>
<% provide(:author, "active") %>





<!--
  card-deck card-group or card-columns div
-->

<div class="row">
  <%= link_to 'New Post', new_authors_post_path, class: 'btn btn-primary btn-lg mb-1' %>

  
  <table class="table table-striped">

    <tr>
      <th colspan="5">Title</th>
      
    </tr>
    
    <%= render @posts %>
  </table>



</div>


<!--

  <p id="notice"><%#= notice %></p>
  
  <h1>Posts</h1>
  
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Description</th>
        <th>Slug</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    
    <tbody>
      <%# @posts.each do |post| %>
      <tr>
        <td><%#= post.title %></td>
        <td><%#= post.body %></td>
        <td><%#= post.description %></td>
        <td><%#= post.slug %></td>
        <td><%#= link_to 'Show', post %></td>
        <td><%#= link_to 'Edit', edit_post_path(post) %></td>
        <td><%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <%# end %>
    </tbody>
  </table>
  
  <br>
  
  <%#= link_to 'New Post', new_post_path %>
  
-->

app/views/authors/posts/new.html.erb
<% provide(:page_title, "New Post") %>
<% provide(:author, "active") %>


<%= render 'form', post: @post, url: authors_posts_url %>

app/views/authors/posts/show.html.erb
<!--
    only showing one post at a time
-->
<% provide(:page_title, @post.title) %>
<% provide(:author, "active") %>

<div>
    <%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Remove', authors_post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-sm btn-danger' %>
</div>

<div class="row mb-3">
  <div class="col">

    <div class="text-center">
      <h1><%= @post.title %></h1>
      
      <h3 class="text-muted">
        Created: <%= @post.date_created %> | 
        Published: <%= @post.date_published %> | 
        Last Updated: <%= @post.date_updated %>
      </h3>

    </div>
    
  </div>
</div>

<div class="row">
  <div class="col-8 mx-auto">
      <%= @post.body.html_safe %>
  </div>
</div>

  